### ISSUE TITLE
Implement adjoint differentiation

### ISSUE THREAD

**Issue by madagra** [pasqal-io/qadence#50] opened 2023-10-09 12:57 UTC
Adjoint differentiation method for computing quantum circuit derivatives. This should allow to save a relevant amount of memory with respect to applying standard backpropagation with `torch.autograd`.

**Comment by dominikandreasseitz** [comment] 2023-11-14 10:45
duplicate of https://github.com/pasqal-io/qadence/issues/97

**Closed by dominikandreasseitz** 2023-11-14 10:45 UTC
Labels: feature, performance
