### ISSUE TITLE
[BugFix] unroll_block_with_scalling  does not always return proper decomposition of pauli terms with coeffs

### ISSUE THREAD

**Issue by rajaiitp** [pasqal-io/qadence#358] opened 2024-02-26 09:36 UTC
```
obs = add(2*kron(2*Z(0), Z(1)), 4 * Z(0))
print("observable:",obs)
terms =[pauli[0] for pauli in unroll_block_with_scaling(obs)]
print("terms:", terms)
coeffs = torch.tensor(
    [pauli[1] for pauli in unroll_block_with_scaling(obs)], dtype=float
)
print("coeffs:",coeffs)
```

observable: AddBlock(0,1)
├── [mul: 2]
│   └── KronBlock(0,1)
│       ├── [mul: 2]
│       │   └── Z(0)
│       └── Z(1)
└── [mul: 4]
    └── Z(0)
terms: [KronBlock(0,1)
├── [mul: 2]
│   └── Z(0)
└── Z(1), Z(0)]
coeffs: tensor([2., 4.])

**Comment by Roland-djee** [comment] 2024-04-05 09:19
Hey @jpmoutinho is this taken care for ?

**Comment by jpmoutinho** [comment] 2024-04-11 15:00
Hey @rajaiitp I was taking a look at this. The issue is that the current block system does not really have the capacity to easily resolve algebraic simplifications like what you encountered. We could code that into it, but this is something that will already be available in the new version. Do you urgently need this?

**Comment by rajaiitp** [comment] 2024-04-29 09:28
Nope, nothing urgent, it can wait. Not a roadblock by any stretch

**Comment by jpmoutinho** [comment] 2024-05-06 10:03
Closing after moving this to the new block system repo.

**Closed by jpmoutinho** 2024-05-06 10:03 UTC
Labels: refactoring
